In [2]:
import pandas as pd
import numpy as np

# Creando un Data Frame:

In [3]:
pd.DataFrame({
    'Id':[1,2,3,4], 
    'CostumerName':['Tom','Harry','Peter','Thomas'],
    'Age':[20,24,34,15]
})

Id CostumerName  Age
0   1          Tom   20
1   2        Harry   24
2   3        Peter   34
3   4       Thomas   15

In [4]:
#Otra forma de construirlo:
pd.DataFrame([[1,'row1'],[2,'row2'],[3,'row3']])

0     1
0  1  row1
1  2  row2
2  3  row3

In [5]:
#Generando numeros random
pd.DataFrame({'Id':np.arange(1,11,1),'Grades':np.random.randint(0,101,10)})

Id  Grades
0   1      32
1   2      49
2   3      89
3   4      45
4   5      29
5   6      41
6   7      91
7   8      25
8   9      90
9  10      31

In [7]:
# Creandolo con valores aleatorios 3 filas y 6 columnas
pd.DataFrame(np.random.rand(3,6))

0         1         2         3         4         5
0  0.475406  0.932654  0.484131  0.044000  0.450116  0.179224
1  0.133953  0.515122  0.760068  0.328764  0.790496  0.723341
2  0.667716  0.262467  0.049123  0.821764  0.335377  0.275360

### Concatenacion de DataFrames

In [8]:
data = pd.DataFrame({'Id':[1,2,3], 'Country':['India','US','Germany']}, index=['x','y','z'])

#creamos una Serie (columna) y le agregamos dos indices solamente
capitals = pd.Series(['Washinton','Berlin'], index=['y','z'])

data

Id  Country
x   1    India
y   2       US
z   3  Germany

In [11]:
#concatenamos los datos con las capitales:
pd.concat([data,capitals],axis=1)

C:\Users\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


Id  Country          0
x   1    India        NaN
y   2       US  Washinton
z   3  Germany     Berlin

# Ordenamiento 
## merge y joins

In [12]:
df1 = pd.DataFrame([['TN','Channai'],
                    ['Karmataka','Bangalore'],
                    ['Telangana','Hyderbad']], columns=['state','capital'])

df2 = pd.DataFrame([['TN','Tamil'],
                    ['Karmataka','Kannada'],
                    ['MP','Hindi'],
                    ['Telangana','Telugu']], columns=['state','Languaje'])

In [13]:
df1

state    capital
0         TN    Channai
1  Karmataka  Bangalore
2  Telangana   Hyderbad

In [14]:
df2

state Languaje
0         TN    Tamil
1  Karmataka  Kannada
2         MP    Hindi
3  Telangana   Telugu

In [15]:
#haciendo merge:

#pd.merge() how=left, rigth, innet and outer 

#la columna pivote es state, recordemos que inner es la interseccion
pd.merge(df1, df2, how='inner', on='state')

state    capital Languaje
0         TN    Channai    Tamil
1  Karmataka  Bangalore  Kannada
2  Telangana   Hyderbad   Telugu

In [16]:
#outer es todo el conjunto:

pd.merge(df1, df2, how='outer', on='state', indicator=True)

state    capital Languaje      _merge
0         TN    Channai    Tamil        both
1  Karmataka  Bangalore  Kannada        both
2  Telangana   Hyderbad   Telugu        both
3         MP        NaN    Hindi  right_only

In [17]:
#Con melt creamos un producto cartesiano con una variable

pd.melt(df1,id_vars='state')

state variable      value
0         TN  capital    Channai
1  Karmataka  capital  Bangalore
2  Telangana  capital   Hyderbad

In [18]:
data = pd.DataFrame({'days':[1,2,3,4,5,6,7,8,9],'temperature':[30,34,35,30,32,31,30,28,25], 'humidity':[30,34,35,30,32,31,30,28,25]})
data

days  temperature  humidity
0     1           30        30
1     2           34        34
2     3           35        35
3     4           30        30
4     5           32        32
5     6           31        31
6     7           30        30
7     8           28        28
8     9           25        25

In [22]:
pd.melt(data,id_vars='days')

#o podemos cambiar el nombre de las columnas:

pd.melt(data,id_vars='days',var_name='Metric', value_name='Humidity/Temperature')

days       Metric  Humidity/Temperature
0      1  temperature                    30
1      2  temperature                    34
2      3  temperature                    35
3      4  temperature                    30
4      5  temperature                    32
5      6  temperature                    31
6      7  temperature                    30
7      8  temperature                    28
8      9  temperature                    25
9      1     humidity                    30
10     2     humidity                    34
11     3     humidity                    35
12     4     humidity                    30
13     5     humidity                    32
14     6     humidity                    31
15     7     humidity                    30
16     8     humidity                    28
17     9     humidity                    25

## Rellenando los campos con NAN

In [19]:
ufo = pd.read_csv('http://bit.ly/uforeports')
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [20]:
#Podemos rellenar los campos que contienen Nan, con strings:
#para ese caso, por ejemplo "no-color"
ufo.fillna({'Colors Reported':'no-color', 'Shape Reported':'no_shape'}, inplace=True)
ufo.head()

City Colors Reported Shape Reported State             Time
0                Ithaca        no-color       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro        no-color          OTHER    NJ  6/30/1930 20:00
2               Holyoke        no-color           OVAL    CO  2/15/1931 14:00
3               Abilene        no-color           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair        no-color          LIGHT    NY  4/18/1933 19:00

## tambien podemos rellenar los campos en nan, con algunos metodos:

#### data.fillna(method='ffill')
#### data.fillna(method='bfill')

### relleno hacia adelante y relleno hacia atras


In [22]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

['a', 'b', 'c'] + [1, 2, 3]

[[0 0 1]
 [1 1 1]]


['a', 'b', 'c', 1, 2, 3]

In [23]:
x = np.arange(36)
x.resize((6,6))
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [9]:
x[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [10]:
x[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [12]:
x.reshape(36)[::7]


array([ 0,  7, 14, 21, 28, 35])

In [14]:
x[[2,3],[2,3]]

array([14, 21])

In [15]:
x[2::2,2::2]


array([[14, 16],
       [26, 28]])

In [16]:
x[2:4,2:4]

array([[14, 15],
       [20, 21]])